QLite version 3.x
#   gem install sqlite3
#   gem install money4Nothing

#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost

  
production:
  <<: *base
  database: pauvco
  username: root
  password: stellina


development:
  <<: *base
  database: pauvco
  username: root
  password: stellina
